### PR TITLE
Extract Duration.balanced out of Duration to keep it internal

### PR DESCRIPTION
**Pull request by SebastianSpeitel**

### CODE REVIEW

**Comment by ColinEberhardt** [comment]
HI @SebastianSpeitel - looks like the unit tests haven't run. Also, the code here hasn't been updated with the change:

https://github.com/ColinEberhardt/assemblyscript-temporal/blob/refactor/assembly/plaindate.ts#L334

I must admit, I'm not sure about this change in general. I know that the TC39 Temporal API doesn't expose a 'balanced' method, but I don't think it does much harm to add this to the public API if it makes the implementation simpler.

assemblyscript-temporal already deviates from the TC39 API in a number of places.

**Comment by SebastianSpeitel** [comment]
How does this make a difference in simplicity?

**Comment by SebastianSpeitel** [comment]
> HI @SebastianSpeitel - looks like the unit tests haven't run. Also, the code here hasn't been updated with the change:
> 
> https://github.com/ColinEberhardt/assemblyscript-temporal/blob/refactor/assembly/plaindate.ts#L334

I thought `Duration.prototype.balanced` is part of the spec, but it actually isn't.

**Comment by ColinEberhardt** [comment]
On further thought - I do like the look of this change. I've incorporated here: https://github.com/ColinEberhardt/assemblyscript-temporal/pull/59/commits/78e3435a9841664a94740884ee987216ceabc2c8

**Pull request closed without merging**
